######################################################################
##
## Filename: emiss_rs232_bram_vhd_tst.udo
## Created on: Tue Mar 20 01:48:59 PM CET 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
