######################################################################
##
## Filename: emiss_recep_rs232_bram.udo
## Created on: Tue Mar 20 02:01:14 PM CET 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
