######################################################################
##
## Filename: emiss_rs232_vhd_tst.udo
## Created on: Tue Mar 20 02:13:23 PM CET 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
