######################################################################
##
## Filename: recep_rs232.udo
## Created on: Tue Mar 20 10:25:15 AM CET 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
