######################################################################
##
## Filename: recep_rs232_vhd_tst.udo
## Created on: Tue Mar 20 10:23:44 AM CET 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
