# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8.xci
# IP: The module: 'bram_16x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_16x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8.xci
# IP: The module: 'bram_16x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_16x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
