# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath /softl3/modelsim10_5c/modeltech/bin
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-15435-ocaepc21/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.cache/wt [current_project]
set_property parent.project_path /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vhd/ram_16x8.coe
read_vhdl -library xil_defaultlib {
  /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/imports/vhd/emiss_rs232.vhd
  /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/imports/vhd/fsm_write.vhd
  /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/imports/vhd/recep_rs232.vhd
  /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/imports/vhd/emiss_recep_rs232_bram.vhd
}
read_ip -quiet /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8.xci
set_property used_in_implementation false [get_files -all /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/sources_1/ip/bram_16x8/bram_16x8_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/constrs_1/imports/vhd/zedb_emiss_recep_rs232_bram.xdc
set_property used_in_implementation false [get_files /cime-fmr/rollandl-fmr/xilinx/zedboard/emiss_recep_rs232_bram/vivado_2017_4/project_1.srcs/constrs_1/imports/vhd/zedb_emiss_recep_rs232_bram.xdc]


synth_design -top emiss_recep_rs232_bram -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef emiss_recep_rs232_bram.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file emiss_recep_rs232_bram_utilization_synth.rpt -pb emiss_recep_rs232_bram_utilization_synth.pb"
